# Generated by Django 5.1.7 on 2025-03-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='include_rate_cards',
            field=models.ManyToManyField(blank=True, related_name='related_rate_cards', to='rate_card.ratecard'),
        ),
    ]
